### ISSUE TITLE
UpstreamGeodata produce different result from ol matlab-function

### ISSUE THREAD

**Issue by dgustafsson** [rcapell/RHYPE#37] opened 2015-12-09 07:39 UTC
Thanks for the upstreamGeodata function!!
However, I get different results compared to the old matlabfunction I used to use.
It's of course related to branching. 

Is the UpstreamGeodata function handling multiple branches (similar issue as SortGeodata?)

**Comment by rcapell** [comment] 2015-12-09 08:05
Thanks for posting
yes, it uses the same function to find upstream subids
(AllUpstreamSubids()).
My guess is that the problems are caused by branches (bifurcations) which
connect independent basins, ie basins with separate outlet sub-basins
within the model domain.
I have to look at it again, with a suitable testing data set, last week I
did not find the problem...

**Comment by dgustafsson** [comment] 2015-12-09 08:40
actually, both the Matlab function and the current UpstreamGeoData fails to calculate correctly, weighted upstream areas on the attached test cases. The correct upstream area should be
SUBID UP_AREA
1   1
2   1.25
3   2.875
4   2.25
5   5
[geodata-test.txt](https://github.com/rcapell/RHYPE/files/56520/geodata-test.txt)
[branchdata-test.txt](https://github.com/rcapell/RHYPE/files/56521/branchdata-test.txt)

UpstreamGeodata gives this result:
  SUBID MAINDOWN UP_AREA UP_ELEV_MEAN
1     1        3       1            1
2     2        4       2            1
3     3        5       4            1
4     4        5       3            1
5     5        0       5            1

and the matlab gives:
 sumgeo.AREA

ans =

    1.0000
    1.2500
    2.7500
    2.2500
    3.7500

**Comment by dgustafsson** [comment] 2015-12-09 08:42
so UpstreamGeoData is quite close, it adds all the upstream area from the branches, but fails to give weights according to the MAINPART and (1-MAINPART)

**Comment by rcapell** [comment] 2015-12-09 09:21
Disregarding MAINPART is by design. I excluded any consideration of flow
limiting, so that the current results gives only the "connected" upstream
area.
I did this because:
- I thought it was misleading to assume that the MAINPART fraction relates
directly to an area fraction. Discharge might be generated in just a part
of the upstream catchment, so it is has not so much to do with the area
- there are other limiters in BranchData (MAXQMAIN etc.) which I make the
contributrion fraction time-variant.

This dosn't mean of course that we still canadd this if you want it! :)

**Comment by dgustafsson** [comment] 2015-12-10 10:34
Here is a version of the AllUpstreamSubids that returns upstream subid's and corresponding weights if you want to weight the upstream sums and means according to mainpart and 1-mainpart in the branchdata. See example data.

**Comment by dgustafsson** [comment] 2015-12-10 10:35
try to upload a file here :(

**Comment by dgustafsson** [comment] 2015-12-10 10:35
sending email

**Comment by rcapell** [comment] 2015-12-10 11:58
[sumgeodata.zip](https://github.com/rcapell/RHYPE/files/58032/sumgeodata.zip)
putting this her for future ref..

Thanks for this, I try to merge and update this now!

**Comment by dgustafsson** [comment] 2015-12-15 07:54
Here is now also a UpstreamGeodata.R which makes use of the weights from AllUpstreamSubids.R

The modifications in especially AllUpstreamSubids.R are not very efficiently programmed, so running the UpstreamGeodata function on a geodata with +30.000 rows takes some time.

... for some reason I am unavailable to upload any file here...

**Comment by rcapell** [comment] 2016-05-17 16:30
Weights implemented, based on your files. Thanks!
Closing this issue...

**Comment by dgustafsson** [comment] 2016-05-24 03:42
Hi Rene, I have tested the new functions on the test-data I submitted above, but does not get exactly the same results as I derived by hand, and which I could repeat with my code. Did you try this testdata and come up with correct results? With the committed functions (I believe), I got these results for the test-data:
ROW SUBID MAINDOWN UP_AREA UP_ELEV_MEAN HARO UP_RIVLEN
1     1        3 1.00000            1    1   1.00000
2     2        4 1.25000            1    1   1.25000
3     3        5 2.75000            1    1   2.75000
4     4        5 2.25000            1    1   2.25000
5     5        0 4.81250            1    1   4.81250
6     6        7 1.00000            1    2   1.00000
7     7        8 2.68750            1    2   2.68750
8     8        9 3.68750            1    2   3.68750
9     9        0 2.84375            1    2   2.84375

**Comment by dgustafsson** [comment] 2016-05-24 03:51
updated testdata with RIVLEN column
[geodata-test.txt](https://github.com/rcapell/RHYPE/files/278719/geodata-test.txt)

**Comment by dgustafsson** [comment] 2016-05-24 03:54
Results with the dgUpstreamGeoData-function (
[dgUpstreamGeoData.zip](https://github.com/rcapell/RHYPE/files/278723/dgUpstreamGeoData.zip)
) :
ROW SUBID MAINDOWN  UP_AREA UP_ELEV_MEAN HARO UP_RIVLEN
1     1        3 1.000000            1    1  1.000000
2     2        4 1.250000            1    1  1.250000
3     3        5 2.875000            1    1  2.875000
4     4        5 2.250000            1    1  2.250000
5     5        0 6.140625            1    1  6.140625
6     6        7 1.000000            1    2  1.000000
7     7        8 2.718750            1    2  2.718750
8     8        9 3.718750            1    2  3.718750
9     9        0 2.859375            1    2  2.859375

**Comment by dgustafsson** [comment] 2016-05-24 03:55
Already in SUBID 3, the UpstreamGeoData is wrong (2.75 instead of 2.875).

**Comment by rcapell** [comment] 2016-05-24 13:20
I made a mistake in merging duplicates (did not merge them but removed duplicates). Fixed in latest master and tsted with your example files.
closing again.

**Closed by rcapell** 2016-05-24 13:20 UTC

**Comment by dgustafsson** [comment] 2016-05-24 13:23
great! Thanks
